USE AdventureWorks
GO
CREATE DATABASE Session07
GO
USE Session07
GO
CREATE TABLE Person
(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL,
	Family NVARCHAR(50) NOT NULL,
	NationalCode CHAR(10) NOT NULL UNIQUE
)
GO
CREATE TABLE Student
(
	Id INT PRIMARY KEY FOREIGN KEY REFERENCES Person(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	CellPhone CHAR(11) CHECK(CellPhone LIKE '09_________'),
	FatherName NVARCHAR(50),
	CreatedDate DATETIME DEFAULT GETDATE(),
	RowGuid UNIQUEIDENTIFIER DEFAULT NEWID(),
	[RowVersion] TIMESTAMP,
	--UNIQUE(Name,Family,FatherName),
	--CONSTRAINT UQ_Name_Family_FatherName UNIQUE(Name,Family,FatherName)
)
GO
CREATE TABLE Teacher
(
	Id INT PRIMARY KEY FOREIGN KEY REFERENCES Person(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	Experience INT
)
GO
SELECT NEWID()
GO
CREATE TABLE Course
(
	Id INT IDENTITY PRIMARY KEY,
	Title NVARCHAR(50) NOT NULL UNIQUE,
	Duration INT,
	TeacherId INT,
	FOREIGN KEY(TeacherId) REFERENCES Teacher(Id) ON DELETE SET NULL ON UPDATE CASCADE
)
GO
CREATE TABLE Course_Student
(
	CourseId INT,
	StudentId INT,
	PRIMARY KEY(CourseId, StudentId),
	CONSTRAINT FK_CourseId FOREIGN KEY (CourseId) REFERENCES Course(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_StudentId FOREIGN KEY (StudentId) REFERENCES Student(Id) ON DELETE NO ACTION ON UPDATE NO ACTION
)
GO
SELECT * FROM Student
GO
SELECT * 
INTO Product
FROM AdventureWorks.Production.Product
GO
DROP TABLE Product
GO
ALTER TABLE Teacher
ADD EmployeeCode CHAR(8) UNIQUE
GO
ALTER TABLE Teacher
DROP COLUMN Experience
GO
