// <auto-generated />
namespace EFCodeFirstDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class product_category_relation_created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_category_relation_created));
        
        string IMigrationMetadata.Id
        {
            get { return "201806020807487_product_category_relation_created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
