CREATE DATABASE Session12
GO
USE Session12
GO
CREATE TABLE [Log]
(
	Id INT PRIMARY KEY IDENTITY,
	LogText NVARCHAR(50)
)
GO
INSERT INTO [Log] VALUES ('First Entry Before Backup')
GO
INSERT INTO [Log] VALUES ('Entry 08:59')
GO
INSERT INTO [Log] VALUES ('Entry 09:01')
GO
INSERT INTO [Log] VALUES ('Entry 09:39')
GO
USE Session12
GO
USE master
GO
ALTER DATABASE Sesison12
SET MULTI_USER
GO
EXEC sp_who
GO
kill 148
GO
ALTER DATABASE Session12
SET MULTI_USER
WITH ROLLBACK IMMEDIATE
GO

BACKUP DATABASE [Session12] 
TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Backup\Session12_LogBackup_2018-04-07_10-44-40.bak' 
WITH  COPY_ONLY,  RETAINDAYS = 30, NOFORMAT, NOINIT,  NAME = N'Session12-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

