CREATE DATABASE Session13
GO
USE Session13
GO
CREATE TABLE Contact
(
	Id INT PRIMARY KEY IDENTITY,
	PersonId INT,
	[Value] CHAR(15) UNIQUE --INDEX IX_Value -- UNIQUE
	
)
GO
DROP TABLE Contact
GO
CREATE TABLE Contact
(
	Id INT PRIMARY KEY IDENTITY,
	PersonId INT,
	[Value] CHAR(15) INDEX IX_Value -- UNIQUE
	
)
GO
SELECT RAND()
GO
INSERT INTO Contact VALUES(1, CONVERT(CHAR(15), RAND()*1000000))
GO 200000
SELECT * FROM Contact
GO
SELECT * FROM Contact WHERE [Value] = '744442'
GO
SELECT 10/0